// Mock Data for the table
export const employees = [
  {
    id: 1,
    code: "xxxxxx",
    name: "Employee name",
    department: "Department Name",
    designation: "Designation",
    company: "BILLP",
    status: "Permanent",
    image: "/employee.png",
  },
  {
    id: 2,
    code: "xxxxxx",
    name: "Employee name",
    department: "Department Name",
    designation: "Designation",
    company: "BSIBPL",
    status: "Permanent",
    image: "/employee.png",
  },
  {
    id: 3,
    code: "xxxxxx",
    name: "Employee name",
    department: "Department Name",
    designation: "Designation",
    company: "Company",
    status: "Probation",
    image: "/employee.png",
  },
  {
    id: 4,
    code: "xxxxxx",
    name: "Employee name",
    department: "Department Name",
    designation: "Designation",
    company: "Company",
    status: "Permanent",
    image: "/employee.png",
  },
  {
    id: 5,
    code: "xxxxxx",
    name: "Employee name",
    department: "Department Name",
    designation: "Designation",
    company: "Company",
    status: "Probation",
    image: "/employee.png",
  },
  {
    id: 6,
    code: "xxxxxx",
    name: "Employee name",
    department: "Department Name",
    designation: "Designation",
    company: "Company",
    status: "Permanent",
    image: "/employee.png",
  },
];
